Repository node-formidable/formidable, pull requests merged in 2020-12, with the labels that each got.

#662 feat: add min size and empty file validation options
  README.md
  src/Formidable.js
  test/unit/formidable.test.js
Labels: PR: reviewed-approved

#666 feat: add option to store files
  README.md
  examples/log-file-content-to-console.js
  examples/store-files-on-s3.js
  src/Formidable.js
  src/PersistentFile.js
  src/VolatileFile.js
  src/index.js
  src/plugins/octetstream.js
  test/integration/test-file-write-stream-handler-option.js
  test/integration/test-store-files-option.js
  test/unit/persistent-file.test.js
  test/unit/volatile-file.test.js
Labels: PR: partially-approved

#661 adding credits to more folks
  README.md
Labels: PR: unreviewed
