Repository node-formidable/formidable, pull requests merged in 2021-12, with the labels that each got.

#796 fix: PersistentFile.toString() doesn't throw
  src/PersistentFile.js
  test/unit/persistent-file.test.js
Labels: PR: reviewed-approved

#791 File size fix
  CHANGELOG.md
  README.md
  examples/with-http.js
  package.json
  src/Formidable.js
  src/FormidableError.js
Labels: area: file system, PR: unreviewed

#798 fix: do not let empty file on error
  src/PersistentFile.js
Labels: PR: unreviewed

#801 Refactor december
  README.md
  src/Formidable.js
  src/plugins/octetstream.js
  src/plugins/querystring.js
  test/unit/custom-plugins.test.js
Labels: PR: unreviewed
